name: tdk-vault-reference-app
packages:
  - .
scripts:
  test:
    name: test
    description: "test with coverage"
    run: echo "Unit Tests not implemented."
    exec:
      concurrency: 1
  test-integration:
    name: test
    description: "test with coverage"
    run: flutter test integration_test/
    exec:
      concurrency: 1
