name: tdk-vault-reference-app
packages:
  - .
scripts:
  test:
    name: test
    description: "unit test with coverage"
    run: flutter test
    exec:
      concurrency: 1
  test-integration:
    name: test
    description: "integration tests"
    run: flutter test integration_test/
    exec:
      concurrency: 1
